#!sh

for test in ./test/prelude/*.test.coil
do
  echo "Compling '$test'"
  output_file="${test//.\/test\//}"
  output_file="${output_file//.test.coil/}.test.js"
  npm run compile $test test/dist/$output_file
done

deno test