#!sh
mkdir -p dist/test
deno run --allow-read --allow-write ./dist/cli.mjs ./test/algebra.coil ./dist/test/algebra.mjs --std-prefix=../.. &
deno run --allow-read --allow-write ./dist/cli.mjs ./test/collection.coil ./dist/test/collection.mjs --std-prefix=../.. &
wait
deno test ./dist/test/*.mjs
